### PR TITLE
Use prop-types lib to fix deprecations warnings.

### PR DESCRIPTION
**Pull request by filipebarcos**
Accessing PropTypes directly from React is not deprecated and will be
removed entirely from React 16. Currently, we get the following warning

```sh
console.error node_modules/fbjs/lib/warning.js:36
      Warning: Accessing PropTypes via the main React package is
      deprecated. Use the prop-types package from npm instead.
```

This commit adds `prop-types` as dependency and use it as advised.

### CODE REVIEW

**Comment by filipebarcos** [comment]
@yusinto Can you please, take a look at this? Thanks

**Comment by yusinto** [comment]
Hi Filipe I will take a look asap. Thanks for the PR!

**Comment by filipebarcos** [comment]
Hey @yusinto Any news on this one?

**Comment by yusinto** [comment]
Filipe I submitted a couple of pr comments, did you see them?

**Comment by filipebarcos** [comment]
No, there're not comments here..

**Comment by yusinto** [comment]
So if you take a look here https://github.com/yusinto/ld-redux/pull/7

[image: Inline image 1]

**Comment by filipebarcos** [comment]
Seems like your image can't be loaded. 
image

Could you ensure you submitted the comments, specially now that github wraps all comments in a review that you have to submit. Check if your comments have the `pending` label.

image

**Comment by filipebarcos** [comment]
@yusinto Just fixed what you mentioned. You were right, not sure what went wrong in the first place.

**Comment by filipebarcos** [comment]
@yusinto Thanks for merging this.

Do you have an estimate when are you publishing a new version? (sorry to keep pushing)

**Comment by yusinto** [comment]
done

**Pull request merged**
